import { NextResponse } from 'next/server';

function getCircleCoordinates(centerLat: number, centerLng: number, radiusMeters: number): string {
  const points: string[] = [];
  const km = radiusMeters / 1000;
  // 1 degree latitude is approx 111 km
  const latOffset = km / 111.0;
  
  for (let i = 0; i <= 36; i++) {
    const angle = (i * 10 * Math.PI) / 180;
    // Account for longitudinal compression at higher latitudes
    const lngOffset = km / (111.0 * Math.cos((centerLat * Math.PI) / 180));
    
    const pLat = centerLat + latOffset * Math.sin(angle);
    const pLng = centerLng + lngOffset * Math.cos(angle);
    points.push(`${pLng},${pLat},0`);
  }
  return points.join(' ');
}

function getArcCoordinates(centerLat: number, centerLng: number, radiusMeters: number, startAngleDeg: number, endAngleDeg: number): string {
  const points: string[] = [];
  const km = radiusMeters / 1000;
  const latOffset = km / 111.0;
  const steps = 15;
  const stepAngle = (endAngleDeg - startAngleDeg) / steps;
  
  for (let i = 0; i <= steps; i++) {
    const angle = ((startAngleDeg + i * stepAngle) * Math.PI) / 180;
    const lngOffset = km / (111.0 * Math.cos((centerLat * Math.PI) / 180));
    
    const pLat = centerLat + latOffset * Math.sin(angle);
    const pLng = centerLng + lngOffset * Math.cos(angle);
    points.push(`${pLng},${pLat},0`);
  }
  return points.join(' ');
}

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const latParam = searchParams.get('lat');
    const lngParam = searchParams.get('lng');
    const boundaryParam = searchParams.get('boundary');
    const projectName = searchParams.get('project') || 'Permaculture Landscape Plan';

    if (!latParam || !lngParam) {
      return new Response('Missing lat or lng', { status: 400 });
    }

    const lat = parseFloat(latParam);
    const lng = parseFloat(lngParam);

    if (isNaN(lat) || isNaN(lng)) {
      return new Response('Invalid lat or lng', { status: 400 });
    }

    let boundaryCoords: Array<{ lat: number, lng: number }> = [];
    if (boundaryParam) {
      try {
        boundaryCoords = JSON.parse(boundaryParam);
      } catch (err) {
        console.error('KML export parsing boundary coords error:', err);
      }
    }

    // Default boundary if none provided (25m x 100m bounding box approximation)
    if (boundaryCoords.length === 0) {
      const offsetLat = 0.00045; // ~50m
      const offsetLng = 0.00022; // ~25m
      boundaryCoords = [
        { lat: lat + offsetLat, lng: lng - offsetLng },
        { lat: lat + offsetLat, lng: lng + offsetLng },
        { lat: lat - offsetLat, lng: lng + offsetLng },
        { lat: lat - offsetLat, lng: lng - offsetLng },
      ];
    }

    // Close the polygon ring if it isn't closed
    const coordinatesString = boundaryCoords
      .map(c => `${c.lng},${c.lat},0`)
      .concat(boundaryCoords.length > 0 ? [`${boundaryCoords[0].lng},${boundaryCoords[0].lat},0`] : [])
      .join(' ');

    // Calculate concentric zone polygon circles
    const zone1Coords = getCircleCoordinates(lat, lng, 15);
    const zone2Coords = getCircleCoordinates(lat, lng, 35);
    const zone3Coords = getCircleCoordinates(lat, lng, 65);
    const pondCoords = getCircleCoordinates(lat, lng + 0.0002, 6);

    // Calculate swale arcs (curved paths parallel to contours)
    const swaleACoords = getArcCoordinates(lat, lng, 28, 120, 240);
    const swaleBCoords = getArcCoordinates(lat, lng, 50, 120, 240);

    // Calculate shelterbelt line on northeast boundary
    const shelterbeltCoords = `${lng + 0.0003},${lat + 0.0004},0 ${lng + 0.0005},${lat + 0.0002},0 ${lng + 0.0005},${lat - 0.0002},0`;

    // Construct the KML document
    const kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2">
  <Document>
    <name>${projectName} - Permaculture PDC Design Map</name>
    <description>Generated by Permaculture Intelligence Dashboard. High-fidelity regenerative overlays compatible with QGIS and Google Earth Pro.</description>
    
    <!-- Style definitions -->
    <Style id="boundaryStyle">
      <LineStyle>
        <color>ff15803d</color> <!-- Dark green line -->
        <width>3.0</width>
      </LineStyle>
      <PolyStyle>
        <color>2216a34a</color> <!-- Very transparent green fill -->
      </PolyStyle>
    </Style>
    
    <Style id="zone1Style">
      <LineStyle>
        <color>ffa855f7</color> <!-- Purple line -->
        <width>1.5</width>
        <style>dashed</style>
      </LineStyle>
      <PolyStyle>
        <color>15c080f0</color> <!-- Ultra transparent purple fill -->
      </PolyStyle>
    </Style>

    <Style id="zone2Style">
      <LineStyle>
        <color>ff10b981</color> <!-- Emerald line -->
        <width>1.5</width>
      </LineStyle>
      <PolyStyle>
        <color>1510b981</color> <!-- Ultra transparent emerald fill -->
      </PolyStyle>
    </Style>

    <Style id="zone3Style">
      <LineStyle>
        <color>ffd97706</color> <!-- Amber line -->
        <width>1.5</width>
      </LineStyle>
      <PolyStyle>
        <color>0cda8a00</color> <!-- Ultra transparent amber fill -->
      </PolyStyle>
    </Style>

    <Style id="swaleStyle">
      <LineStyle>
        <color>ff0ea5e9</color> <!-- Cyan line -->
        <width>4.0</width>
      </LineStyle>
    </Style>

    <Style id="pondStyle">
      <LineStyle>
        <color>ff0284c7</color> <!-- Light blue line -->
        <width>2.0</width>
      </LineStyle>
      <PolyStyle>
        <color>66bae6fd</color> <!-- Transparent blue water fill -->
      </PolyStyle>
    </Style>

    <Style id="shelterbeltStyle">
      <LineStyle>
        <color>ff14532d</color> <!-- Forest green line -->
        <width>5.0</width>
      </LineStyle>
    </Style>

    <!-- Folder: Settlements -->
    <Folder>
      <name>Zone 0 Homestead &amp; Assets</name>
      <open>1</open>
      <Placemark>
        <name>Zone 0: Primary Settlement (House)</name>
        <description>The primary living space, center of high human activity and main roof water catchment surface.</description>
        <Point>
          <coordinates>${lng},${lat},0</coordinates>
        </Point>
      </Placemark>
      <Placemark>
        <name>20,000L Rainwater Cistern</name>
        <description>Elevated storage tank positioned for gravity-fed drip irrigation supply to Zone 1.</description>
        <Point>
          <coordinates>${lng - 0.0001},${lat + 0.0001},0</coordinates>
        </Point>
      </Placemark>
      <Placemark>
        <name>Solar Array Placement</name>
        <description>Clean energy PV array angled 15 degrees South for optimal year-round solar capture.</description>
        <Point>
          <coordinates>${lng - 0.0002},${lat - 0.0001},0</coordinates>
        </Point>
      </Placemark>
    </Folder>

    <!-- Folder: Land Boundaries & Concentric Zones -->
    <Folder>
      <name>Boundaries and Zoning</name>
      <open>1</open>
      <Placemark>
        <name>Property Boundary</name>
        <description>The outer geographic limits of the permaculture project area.</description>
        <styleUrl>#boundaryStyle</styleUrl>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              <coordinates>${coordinatesString}</coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
      </Placemark>
      <Placemark>
        <name>Zone 1: Intensive Kitchen Garden</name>
        <description>Zone 1 sector receives daily visits. Highly intensive annual crops, raised vegetable beds, compost loops, and grafting nursery.</description>
        <styleUrl>#zone1Style</styleUrl>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              <coordinates>${zone1Coords}</coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
      </Placemark>
      <Placemark>
        <name>Zone 2: Semi-Intensive Agroforestry</name>
        <description>Zone 2 sector houses perennial guilds, fruit orchards (Baobab, Mango, Moringa, Cashew), and gravity drip networks.</description>
        <styleUrl>#zone2Style</styleUrl>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              <coordinates>${zone2Coords}</coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
      </Placemark>
      <Placemark>
        <name>Zone 3: Grazing &amp; Broadscale Crops</name>
        <description>Zone 3 sector houses pasture rotation crops, grain fields, and animal cycling structures.</description>
        <styleUrl>#zone3Style</styleUrl>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              <coordinates>${zone3Coords}</coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
      </Placemark>
    </Folder>

    <!-- Folder: Hydrological Works -->
    <Folder>
      <name>Hydrology Earthworks</name>
      <open>1</open>
      <Placemark>
        <name>Contour Swale A</name>
        <description>Passive earthwork trench on contour designed to intercept sheet flow runoff and hydrate Zone 2.</description>
        <styleUrl>#swaleStyle</styleUrl>
        <LineString>
          <tessellate>1</tessellate>
          <coordinates>${swaleACoords}</coordinates>
        </LineString>
      </Placemark>
      <Placemark>
        <name>Contour Swale B</name>
        <description>Secondary level swale capturing sheet flow runoff and storing subsoil hydration buffers.</description>
        <styleUrl>#swaleStyle</styleUrl>
        <LineString>
          <tessellate>1</tessellate>
          <coordinates>${swaleBCoords}</coordinates>
        </LineString>
      </Placemark>
      <Placemark>
        <name>Zone 2 Infiltration Pond</name>
        <description>A bio-retention pond located at a natural low point to capture contour overflow and recharge local groundwater.</description>
        <styleUrl>#pondStyle</styleUrl>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              <coordinates>${pondCoords}</coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
      </Placemark>
    </Folder>

    <!-- Folder: Shelterbelts -->
    <Folder>
      <name>Shelterbelts and Windbreaks</name>
      <open>1</open>
      <Placemark>
        <name>Northeast Harmattan Windbreak</name>
        <description>Tiered multi-row shelterbelt blocks planted with Neem, Acacia, and Prosopis to buffer dry Sahelian wind vectors.</description>
        <styleUrl>#shelterbeltStyle</styleUrl>
        <LineString>
          <tessellate>1</tessellate>
          <coordinates>${shelterbeltCoords}</coordinates>
        </LineString>
      </Placemark>
    </Folder>
  </Document>
</kml>`;

    return new Response(kml, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.google-earth.kml+xml',
        'Content-Disposition': `attachment; filename="${projectName.replace(/\s+/g, '_')}_design.kml"`,
      },
    });

  } catch (err: any) {
    console.error('KML Exporter crash:', err);
    return new Response('Failed to compile KML file', { status: 500 });
  }
}
